import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="pt-24 min-h-screen">
      <div className="max-w-3xl mx-auto px-6 lg:px-8 py-12">
        <Link
          href="/"
          className="inline-block text-sm tracking-widest uppercase text-[var(--color-silver)] hover:text-[var(--color-ivory)] mb-8 transition"
        >
          ← Home
        </Link>
        <p className="text-xs tracking-[0.3em] uppercase text-[var(--color-champagne)] mb-2">
          Legal
        </p>
        <h1 className="text-3xl md:text-4xl font-light text-[var(--color-ivory)] tracking-wide mb-6">
          Privacy Policy
        </h1>
        <p className="text-[var(--color-silver)] text-sm mb-6">
          This Privacy Policy explains what information we collect, how we use it, and the choices
          you have. It should be treated as a starting point and refined with legal counsel.
        </p>
        <div className="space-y-6 text-sm text-[var(--color-silver)] leading-relaxed">
          <section>
            <h2 className="text-base font-medium text-[var(--color-ivory)] mb-1">
              1. Information we collect
            </h2>
            <p>
              We collect information you provide directly (such as email, display name, profile
              details, photos, preferences) and information generated by your use of the platform
              (such as messages, session metadata, and basic device information).
            </p>
          </section>
          <section>
            <h2 className="text-base font-medium text-[var(--color-ivory)] mb-1">
              2. How we use your information
            </h2>
            <p>
              We use your information to operate and improve Escorta, including account
              authentication, matching, messaging, live/video sessions, safety and moderation, and
              analytics that help us understand how the platform is used.
            </p>
          </section>
          <section>
            <h2 className="text-base font-medium text-[var(--color-ivory)] mb-1">
              3. How we share information
            </h2>
            <p>
              We do not sell your personal information. We may share data with service providers
              (such as hosting, storage, analytics, or payment providers) who help us run the
              service, under agreements that require them to protect your data. We may also share
              information if required by law or to protect our rights or other users.
            </p>
          </section>
          <section>
            <h2 className="text-base font-medium text-[var(--color-ivory)] mb-1">
              4. Data retention
            </h2>
            <p>
              We retain your data for as long as your account is active or as needed to provide the
              service, comply with legal obligations, resolve disputes, and enforce our agreements.
              You may request deletion of your account, after which we will delete or anonymise your
              personal data where feasible.
            </p>
          </section>
          <section>
            <h2 className="text-base font-medium text-[var(--color-ivory)] mb-1">
              5. Your choices
            </h2>
            <p>
              You can update your profile information from your dashboard. In future versions, we
              will provide tools to download a copy of your data and to fully delete your account,
              subject to any legal or safety retention requirements.
            </p>
          </section>
          <section>
            <h2 className="text-base font-medium text-[var(--color-ivory)] mb-1">
              6. Security
            </h2>
            <p>
              We use reasonable technical and organisational measures to help protect your data.
              However, no system is completely secure, and we cannot guarantee absolute security of
              your information.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

